{% set version = "7.8.5" %}

package:
  name: ipywidgets
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipywidgets/ipywidgets-{{ version }}.tar.gz
  sha256: 927439399d75f59f43864c13d7e73b05a4de522d3ea09d6048adc5c583b55c3b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.3
    - setuptools
  run:
    - comm >=0.1.3
    - ipython >=4.0.0
    - ipython_genutils >=0.2.0,<0.3.0
    - jupyterlab_widgets >=1.0.0,<3
    - python >=3.3
    - traitlets >=4.3.1
    - widgetsnbextension >=3.6.10,<3.7.0

test:
  requires:
    - pip
  imports:
    - ipywidgets
  commands:
    - pip check

about:
  home: https://github.com/ipython/ipywidgets
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Jupyter Interactive Widgets
  description: |
    ipywidgets are interactive HTML widgets for Jupyter notebooks and the IPython kernel.
  doc_url: https://ipywidgets.readthedocs.io
  doc_source_url: https://github.com/jupyter-widgets/ipywidgets/blob/master/docs/source/index.rst

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
    - SylvainCorlay
    - willingc
    - jasongrout
    - maartenbreddels
    - pbugnion
    - jtpio
    - martinRenou
    - vidartf
    - bollwyvl
