{% set version = "8.1.4" %}

package:
  name: ipywidgets
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipywidgets/ipywidgets-{{ version }}.tar.gz
  sha256: 85b5ef93ed4c809ab3bae892dd17bc6768590fde108cd987ce8321e6991f3139

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=40.8.0
    - wheel
  run:
    - comm >=0.1.3
    - ipython >=6.1.0
    - jupyterlab_widgets >=3.0.11,<3.1.0
    - python >=3.7
    - traitlets >=4.3.1
    - widgetsnbextension >=4.0.11,<4.1.0
test:
  requires:
    - coverage
    - ipykernel
    - jsonschema
    - pip
    - pytest <8
    - pytz
  imports:
    - ipywidgets
  commands:
    - pip check
    - coverage run --source ipywidgets --branch -m pytest -vv --color=yes --tb=long --pyargs ipywidgets
    - coverage report --show-missing --skip-covered --fail-under=90

about:
  home: https://github.com/jupyter-widgets/ipywidgets
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Jupyter Interactive Widgets
  description: |
    ipywidgets are interactive HTML widgets for Jupyter notebooks and the IPython kernel.
  doc_url: https://ipywidgets.readthedocs.io/en/latest/
  doc_source_url: https://github.com/jupyter-widgets/ipywidgets/blob/master/docs/source/index.rst

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
    - SylvainCorlay
    - willingc
    - jasongrout
    - maartenbreddels
    - pbugnion
    - jtpio
    - martinRenou
    - vidartf
    - bollwyvl
