{% set version = "8.0.0rc0" %}
{% set sha256 = "9bc4440b6d669aa946075d10360ded2a76dbcf462f5212b9310e9b189ed84574" %}

package:
  name: ipywidgets
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipywidgets/ipywidgets-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - ipython >=4.0.0
    - ipykernel >=4.5.1
    - traitlets >=4.3.1
    - nbformat >=4.2.0
    - widgetsnbextension >=4.0.0rc0,<5.0.0
    - jupyterlab_widgets >=3.0.0rc0,<4.0.0
    - ipython_genutils >=0.2.0,<0.3.0

test:
  imports:
    - ipywidgets

about:
  home: https://github.com/ipython/ipywidgets
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Jupyter Interactive Widgets
  description: |
    ipywidgets are interactive HTML widgets for Jupyter notebooks and the IPython kernel.
  doc_url: https://ipywidgets.readthedocs.io/en/latest/
  doc_source_url: https://github.com/jupyter-widgets/ipywidgets/blob/master/docs/source/index.rst

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
    - SylvainCorlay
    - willingc
    - jasongrout
    - maartenbreddels
    - pbugnion
    - martinRenou
