{% set version = "7.7.3" %}

package:
  name: ipywidgets
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipywidgets/ipywidgets-{{ version }}.tar.gz
  sha256: b41ca84d2742e39f2a730a13ea0dd619fca62e56cfac88c8f08989fb00a54fa8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.3
  run:
    - ipython >=4.0.0
    - ipython_genutils >=0.2.0,<0.3.0
    - jupyterlab_widgets >=1.0.0,<3
    - python >=3.3
    - traitlets >=4.3.1,<6.0.0
    - widgetsnbextension >=3.6.0,<3.7.0

test:
  requires:
    - pip
    - pytest-cov
  imports:
    - ipywidgets
  commands:
    - pip check
    - pytest -vv --pyargs ipywidgets --cov=ipywidgets --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=92

about:
  home: https://github.com/ipython/ipywidgets
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Jupyter Interactive Widgets
  description: |
    ipywidgets are interactive HTML widgets for Jupyter notebooks and the IPython kernel.
  doc_url: https://ipywidgets.readthedocs.io
  doc_source_url: https://github.com/jupyter-widgets/ipywidgets/blob/master/docs/source/index.rst

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
    - SylvainCorlay
    - willingc
    - jasongrout
    - maartenbreddels
    - pbugnion
    - jtpio
    - martinRenou
    - vidartf
    - bollwyvl
