{% set version = "5.1.5" %}

package:
  name: ipywidgets
  version: {{ version }}

source:
  fn: ipywidgets-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/i/ipywidgets/ipywidgets-{{ version }}.tar.gz
  md5: 7016f12e633d0f7c91d968eb8c8330d1

build:
  number: 0
  script: python -m pip install --no-deps .

requirements:
  build:
    - python
  run:
    - python
    - ipython >=4.0.0
    - ipykernel >=4.2.2
    - traitlets >=4.2.1
    - widgetsnbextension >=1.2.3

test:
  imports:
    - ipywidgets

about:
  home: https://github.com/ipython/ipywidgets
  license: BSD 3-clause
  summary: Widgets for the Jupyter Notebook

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
    - SylvainCorlay
    - willingc
