{% set version = "5.2.3" %}
{% set sha256 = "833bfd14f70ef692724aec01d5adeae068cdab7c86123f37f7e9742a2988e648" %}

package:
  name: ipywidgets
  version: {{ version }}

source:
  fn: ipywidgets-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/i/ipywidgets/ipywidgets-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - ipython >=4.0.0
    - ipykernel >=4.2.2
    - traitlets >=4.2.1
    - widgetsnbextension >=1.2.6, ==1.*

test:
  imports:
    - ipywidgets

about:
  home: https://github.com/ipython/ipywidgets
  license: BSD 3-clause
  license_file: COPYING.md
  summary: Jupyter Interactive Widgets

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
    - SylvainCorlay
    - willingc
    - jasongrout
