travis:
  secure:
    BINSTAR_TOKEN: METVb7yCPw98OSd/nqdPrmMZ8SRSWzey0N/jd6BPziNKH5XxhNInycne4SkRcO8yvEHliOI3twCFOAkxVZTPkPL7K4pw+qEL8hnWd8BZcG3eVCKc85TeJK0bmS8jaK0TZ133ZSG4+M7yenCF5behmyoD0cddCmbP0hhoZq4gWi76UkNP4IHDHpfHNZkd/CHBKMj5M5g2nNCxBLDm+V7gyasG11ttLRW/J+TvSYKyOihl+bpClpO6ibYgcOcEg3Ea6w6Db8cY2BLAo+DkKNqKQQpy1cl7NxIdDY5Otn9nsHJcg6eakSMgAOnsbAVl3VkcofE0yxKL7GwR0B//fF3KxGKK+9nUJB44Nc3Tfh7foRM+hjShGWwNQ27Nd4ASa430SGmtOTjwzyYU3D2gfUxojLHI0bUDh6eEz+2ovCDWQ5G/t2KnuDImBivWcBWtTgYsFTMzS2thVNfYAR1538n65DSbVgsEb7l7pweWcOIWuJ9pIFOFkbY9aPtWxIv6eKKJQ7EdM+lQcgWjako1p/QdbW77VrAVyNAAVnN/jM3oRAdnFryFzI9UjdccXxIO7U3HzQoTn5GqvH3ahZ/ySnS2FaaYj4KfKokzk3h1GMj81b5LrFc3Lmizy/avuxnezpQH+ITHfN83EMo8nHlXy4iKY5hcm3BcSKO+rBUCqCZdcm0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
